# Generated by Django 2.0 on 2018-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180112_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
