# Generated by Django 2.0 on 2018-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
