# Generated by Django 2.0 on 2018-01-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180115_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='api.Event'),
        ),
    ]
