# Generated by Django 2.0 on 2018-01-18 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180115_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='projects',
            field=models.ManyToManyField(to='api.Project'),
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
