export default {
    token: '',
    user: {},
    errors: [],
    students: [],
    projects: [],
    users: [],
    events: [],
    currentEvent: {},
    currentEventStudentsList: [],
    pastMeetings: [],
    studentsFromPastMeetings: [],
    currentMeeting: {},
    currentStudent: {},
    currentStudentImplementations: [],
    currentImplementation: {},
    currentScore: {},
    currentMeetings: [],
    implementations: [],
    scores: [],
}
  